### ISSUE TITLE
After reset , Adso keeps objects from previous game

### ISSUE THREAD

**Issue by luzbel** [Samuel85/Abbey#1]
Not sure if this applies to Abbey port, but I miss that fix  https://github.com/luzbel/VigasocoSDL/commit/cde222d6198acdbe49ad7f3697799c904f0ecf67

**Comment by Samuel85** [comment]
yeah, I saw the same mistake. Will work on that. 

Hey Luzbel, if you are still active with this project maybe we should work together. My problem now is the lack of time to completely understand how the old vigasoco's code works before to improve it. I want to improve the limitations on the old rom, like the aspect ratio and the old font characters and finally to make a Nintendo 3ds port to use both screens for the game and the map.

**Comment by luzbel** [comment]
I don't have so much time for the project and most of the time is focused on https://github.com/LaAbadIAdelCrimen/VigasocoSDL-AI , but sure we can work together. 

Would be great if we can keep the "game" code synchronised, and only have differences in the "framework" . Totally agree on Vigasoco was designed to create a framework for the design of games and most of these features are beyond this project's scope, making the maintenance of the code more difficult."

For the understanding of the code, the reference is  https://github.com/GuillianSeed . He is the author of MSX2 version, J2ME, Java version and the Extensum version.

**Comment by Samuel85** [comment]
Fixed.
