### ISSUE TITLE
menus are not working properly in linux version with keyboard

### ISSUE THREAD

**Issue by luzbel** [Samuel85/Abbey#4]

**Comment by Samuel85** [comment]
yeah, you are right. I never got any feedback about the game and most of the time I play it using a pad or running on android or the RG350. Such an honor Luzbel to see you trying this version. I remember your name from the credits on the original SDL version.  Will definitely work on that.

**Comment by luzbel** [comment]
seems LSHIFT is used to select menus with keyboard instead space or return

**Comment by Samuel85** [comment]
va!, he redefinido las teclas para PC.
