### ISSUE TITLE
Help building, please

### ISSUE THREAD

**Issue by vanfanel** [Samuel85/Abbey#5]
Hello there @Samuel85 

I absolutely love the idea of this modernization of the Vigasoco project for natively running "la Abadía" :)

I am trying to build it from the CMakefile.txt, but it seems to be having some trouble finding some source files. But where are those? I think the CMakeLists.txt file needs some small adjustment for it's maker or creator! :P

```
manuel@hp15db0:~/src/Abbey/b4$ cmake ..
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
<FindSDL2.cmake>
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
</FindSDL2.cmake>
-- Found SDL2: /usr/lib/libSDL2main.a;/usr/lib/libSDL2.so;-lpthread  
-- Found SDL2_mixer: /usr/lib/libSDL2_mixer.so (found version "..") 
-- Found SDL2_ttf: /usr/lib/libSDL2_ttf.so (found version "..") 
-- Configuring done
CMake Error at CMakeLists.txt:39 (add_executable):
  Cannot find source file:

    ConfigReader/configreader.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at CMakeLists.txt:39 (add_executable):
  No SOURCES given to target: abbey


CMake Generate step failed.  Build files cannot be regenerated correctly.

```

My plan for this is having la Abadía running natively on the Raspberry Pi... without X! Directly on the TTY, thanks to my own KMS/DRM backend for SDL2 (best way to play games on GNU/Linux, if you ask me: no input lag due to the X11 server, etc). But I need this smaaaall help here-

Thanks Samuel!

Manuel

**Comment by Samuel85** [comment]
Hi Manuel. This is my fault, for some reason if you clone Abbey it doesn't copy the files from another project of mine "ConfigReader". (https://github.com/Samuel85/ConfigReader)

I will try to fix this problem, but I think the shortest way now is to just copy configreader.cpp, configreader.h, and singlelinkedlist.h to the ConfigReader folder inside of Abbey. *If you know how to fix it please let me know, I'm still a newbie of Git.

Please tell me more about this KMS/DRM backend project, sounds really interesting and I'm planing to buy a Piboy DMG with a raspberry pi 4 to try the game, maybe I will need it.

**Comment by vanfanel** [comment]
@Samuel85 

I you copy the files to the expected place and do:
```
git add .
git commit -m "copy needed files from ConfigReader"
git push origin master
```
..the the intended files should be in place on the repo :)

KMSDRM is not exactly a project, but a mature graphics backend for SDL2.
You simply have to build SDL2 with the `--enable-video-kmsdrm` configure option, and you SDL2 games will run without stinkin' X11 server!

I would recommend you to install these dependencies first:
`
sudo apt-get install libudev-dev libasound2-dev libvorbis-dev libflac-dev libmodplug-dev libpng-dev libjpeg-dev libfreetype6-dev --no-install-recommends`

You will also need the dev libs for libGBM, libDRM and MESA.
For a Pi4 based handheld,  no X11 should be the way to go!

**Comment by Samuel85** [comment]
Hey thanks!, it works now. I checked the project and it compiles without any problem.

**Comment by vanfanel** [comment]
@Samuel85 Yes, just built it too and made it work on KMSDRM, no X11 :)

However, screen refresh is a bit odd in KMSDRM mode.
How are you doing the screen refresh? What rate are you using? I have seen this behaviour on other SDL2 programs and it may be an internal backend problem I would like to look into.

**Comment by Samuel85** [comment]
I think I know the problem. The game fixes the frame rate, with the RG350 I found that I need to tweak this value in order to make the scroll run faster, so maybe this is the same problem with the raspberry pi. Fixing the frame rate is desirable as you could end up making the game to take more resources than needed and is really noisy if you run it on a laptop,

This is done here:
Game::mainLoop()
...
		//cap the frame rate
		if (SDL_GetTicks() - frameTime < sys->minimumFrameTime){
			SDL_Delay(sys->minimumFrameTime - (SDL_GetTicks() - frameTime));
		}

but you just need to tweak:

system.h:

#define GAME_FRAME_TIME 130
#define SCROLL_FRAME_TIME 10

Maybe at some point I will need to calculate the correct values at run time, is really interesting to see this port running on other platforms.

**Comment by vanfanel** [comment]
@Samuel85
I have tried that and it doesn't seem to be the problem: what I see in KMSDRM mode are frames being repeated (ie: some previous frames are shown again).

Do you use any 8bpp surfaces or textures? I am looking at the code but I don't see anything strange. You seem to:
-Draw the game graphics to a software surface
-Update a texture from that surface
-RenderCopy the texture to the renderer
-RenderPresent the renderer

Which looks like a typical SDL2 graphics loop. Am I missing something in between? 

EDIT: Could it be that you are somehow doing a RenderPresent on a non-updated texture under certain circumstances, or something like that?

**Comment by Samuel85** [comment]
maybe this is the problem in system.cpp:

surface = SDL_CreateRGBSurface(0, TEXTURE_WIDTH,TEXTURE_HEIGHT,**32**, rmask, gmask,bmask, amask);

Please send me a picture of the error, maybe I can understand the problem this way.

**Comment by vanfanel** [comment]
@Samuel85 I can't send you a picture because it's an animation problem (ie: each frame looks perfect, but pacing is not correct).
I am doing a test program that will copy your timmings and internal SDL2 formats, so I can see what's causing this.
It will take some time for me to complete these experiments on the SDL2 side and on the KMSDRM side, so don't worry, it's possibly not the fault of this engine, it's just that finding the problem in a small engine will help me to debug it.

**Comment by vanfanel** [comment]
@Samuel85 I have been replicating your code and timings as I said. For that I did an small test program:
https://github.com/vanfanel/LBE_DOCS/blob/master/SDL2_2D_TEXTURE_FROM_SURFACE/ppp.c

Thing is, using the same screen update methods that you use, I can't replicate the "duplicated frames" issue.

The only thing I have yet to replicate is the threaded graphics rendering, which you seem to do here:
https://github.com/Samuel85/Abbey/blob/f0360c8cede10967038b01b47fbe36e053af8358/vigasoco/AbadiaDriver.cpp#L271

...but I don't see any access protection around `surface->pixels` , which you access here for screen rendering:
https://github.com/Samuel85/Abbey/blob/f0360c8cede10967038b01b47fbe36e053af8358/vigasoco/AbadiaDriver.cpp#L272

So, are you accessing a surface without any mutex or other multithreaded access protection mechanism?

And another question: were is the thread writing into `surface->pixels`?

**Comment by Samuel85** [comment]
Hi, 
I'm not using threads. So it's not a problem to just access to surface->pixels.
The original code used threads functions from the SDL library, but I removed all references and rewrote the loops that needed. The only threads is due to SDL_mixer, but it's not related to the game.

The comment "// dibuja los datos que el juego escribe en el otro hilo en el buffer de pantalla" is from the original vigasoco project. You can find the same line in luzbel's vigasoco repository. I need to clean that line from my project.

Maybe you need to replicate how AbadiaDriver::render works with your test program.
I wrote that ugly for ... and two more for loops inside because the original project saved some memory by compressing the image in half, and writes line twice vertically.

**Comment by vanfanel** [comment]
Ah, found the problem Samuel. Wow, wasn't it a big experiment for such an insignificant problem, how typical! :)

The problem is very easy to fix:
You are not calling
`SDL_RenderClear(renderer);`
before calling
`SDL_RenderCopy(renderer, texture, NULL, NULL);`

As you will see here: 
https://gist.github.com/Twinklebear/8265888#file-main-cpp-L33

and here

https://lazyfoo.net/tutorials/SDL/43_render_to_texture/index.php

...doing an SDL_RenderClear() call before each SDL_RenderCopy() call to render to texture is common practice. I will ask Slouken about this, because I am still somewhat puzzled that Abbey gets away without this on X11 but explodes under KMSDRM.

**Comment by Samuel85** [comment]
Awesome!, thanks for sharing the fix. I will include it to the project.

**Comment by vanfanel** [comment]
@Samuel85 Thanks to you! It was nice to find and understand such a project. And it helped me to understand the underlying problem too (but I think we have speaking english for no reason because we're both spanish if I'm not mistaken).

**Comment by Samuel85** [comment]
Hola Manuel ...bueno ambos somos hispanos. También me imaginé que eras Español al ver tus dos apellidos. Yo soy mexicano, aunque tengo muy buenos recuerdos de tu país pues viví en Madrid un par de años. 

Respecto a Abbey, encontré un pequeño gran error que por accidente no vi. Una función (GeneradorPantallas::dibujaBufferTiles) que redibujaba varias veces la pantalla al seguir usando código de vigasoco. 
Tal vez esto podría haber echo mas lento el video en la raspberry pi. 

¿Por cierto, te ha dicho algo Slouken?

**Comment by vanfanel** [comment]
Ya me parecía que estábamos haciendo el canelo hablando los dos en gringo! :)
Yo soy de España. ¿Ahí en México también pegó fuerte La Abadía?

Pues tengo que volver a probarlo si arreglas ese error que dices, porque sí que iba algo lento en la Pi.
Y el aspect ratio de la pantalla del título no parece correcto. SDL2 te lo arregla con SDL_SetLogicalRenderSize().

Slouken me ha dicho esto:

_The state of the framebuffer is not defined at the start of the frame and a render clear is always the first thing you do. The state of a render target is defined, it’s the last contents that you put into it._

Así que creo que usar SDL_RenderClear() antes de RenderCopy es buena idea.

**Comment by Samuel85** [comment]
En México no llegó la abadía, aunque estoy seguro que lo habría petado. Lamentablemente en los 80s sólo nos llegaron computadoras hechas en Estados Unidos (mayormente por Atari) y pues técnicamente eran inferiores al CPC, por lo que nunca nos llegó la abadía del crimen. Yo supe de este juego a principios del 2000 por un fanzine español (Aula Macedonia), por una entrevista que le hizo a Antonio Giner.

Ya he corregido GeneradorPantallas::dibujaBufferTiles. Este fin de semana he hecho un port para Vita y al ser mas lenta pude ver que algo estaba mal en esa función.

Sobre la pantalla de inicio ya se me hacía muy raro que cubriera la relación 4:3 de la pantalla. La abadía tiene una resolución muy extraña que supongo viene del CPC.

Respecto a tu correción, voy a incorporarla lo antes posible, necesito antes problarla en todos los demás ports que mantengo para ver si no causa problemas.
