### ISSUE TITLE
Hice un Port para psvita

### ISSUE THREAD

**Issue by skywalker952** [Samuel85/Abbey#7]
Gracias a este port y despues de mucho tiempo intentando portar vigasocosdl directamente no pude (iba muy lento),asi que muchas gracias,dime si prefieres un fork o que te de los sources o que no haga nada,gracias de nuevo

**Comment by Samuel85** [comment]
Excelente! yo me compré una psvita con la misma intención aunque aun no me he metido ver como instalar el toolchain para compilar para vita. 
Pues si no has tocado el código, creo que lo mas sencillo sería hacer una carpeta "build_vita" y algún script para compilarlo para esta plataforma. Lo dejo a tu consideración si te gustaría hacer un fork o si gustas aportar los cambios a este proyecto.
A mi me haría mucha ilusión ver como corre en la vita. Tienes algún video en youtube del juego o fotografía?.

**Comment by skywalker952** [comment]
cmake_minimum_required(VERSION 2.8)

if(NOT DEFINED CMAKE_TOOLCHAIN_FILE)
  if(DEFINED ENV{DOLCESDK})
    set(CMAKE_TOOLCHAIN_FILE "$ENV{DOLCESDK}/share/dolce.toolchain.cmake" CACHE PATH "toolchain file")
  else()
    message(FATAL_ERROR "Please define DOLCE to point to your SDK path!")
  endif()
endif()

project(abbey)
include("${DOLCESDK}/share/dolce.cmake" REQUIRED)

set(VITA_APP_NAME "Abbey")
set(VITA_TITLEID  "ABBEY0001")
set(VITA_VERSION  "01.00")

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS}  -Wl,-q -Wall -fno-lto -std=c++11")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}  -Wl,-q -Wall -fno-lto -std=c++11")

file(GLOB_RECURSE vigasoco_core_SOURCES "vigasoco/*.cpp")
file(GLOB_RECURSE vigasoco_SOURCES "src/*.cpp")

include_directories(
  src
  vigasoco
  SDL2
)


add_executable(${PROJECT_NAME} ${vigasoco_SOURCES} ${vigasoco_core_SOURCES}  ConfigReader/configreader.cpp
)

target_link_libraries(${PROJECT_NAME}
  SDL2_ttf
  SDL2_mixer
  SDL2
  debugnet
  pib
  libScePiglet_stub
  SceNetCtl_stub
	SceNet_stub
  SceCtrl_stub
  SceAudio_stub  
  SceGxm_stub
  SceCommonDialog_stub
  SceMotion_stub
  SceTouch_stub
  SceHid_stub
  SceDisplay_stub
  SceDisplayUser_stub
  SceSysmodule_stub
  FLAC
  mikmod
  mpg123
  freetype
  png
  vorbisfile
  vorbis
  ogg
  z
)

dolce_create_self(${PROJECT_NAME}.self ${PROJECT_NAME})
dolce_create_vpk(${PROJECT_NAME}.vpk ${VITA_TITLEID} ${PROJECT_NAME}.self
  VERSION ${VITA_VERSION}
  NAME ${VITA_APP_NAME}
  FILE build_vita/sce_sys/icon0.png sce_sys/icon0.png
  FILE build_vita/sce_sys/livearea/contents/bg.png sce_sys/livearea/contents/bg.png
  FILE build_vita/sce_sys/livearea/contents/startup.png sce_sys/livearea/contents/startup.png
  FILE build_vita/sce_sys/livearea/contents/template.xml sce_sys/livearea/contents/template.xml
  FILE build_vita/fonts/arial.ttf fonts/arial.ttf
  FILE build_vita/roms/abadia/abadia.dsk roms/abadia/abadia.dsk
  FILE build_vita/roms/abadia/GraficosCPC roms/abadia/GraficosCPC
  FILE build_vita/roms/abadia/GraficosVGA roms/abadia/GraficosVGA
  FILE build_vita/roms/abadia/abrir.wav roms/abadia/abrir.wav 
  FILE build_vita/roms/abadia/aporrear.wav roms/abadia/aporrear.wav 
  FILE build_vita/roms/abadia/campanas.wav roms/abadia/campanas.wav 
  FILE build_vita/roms/abadia/cerrar.wav roms/abadia/cerrar.wav 
  FILE build_vita/roms/abadia/coger.wav roms/abadia/coger.wav 
  FILE build_vita/roms/abadia/dejar.wav roms/abadia/dejar.wav 
  FILE build_vita/roms/abadia/espejo.wav roms/abadia/espejo.wav 
  FILE build_vita/roms/abadia/fondo.wav roms/abadia/fondo.wav 
  FILE build_vita/roms/abadia/pasos.wav roms/abadia/pasos.wav 
  FILE build_vita/roms/abadia/tintineo.wav roms/abadia/tintineo.wav 

)

**Comment by Samuel85** [comment]
he conseguido hacer funcionar Abbey en Vita. Corregí una función que por error redibujaba varias veces la pantalla al hacer una transición de pantallas, agregué un par de sonidos que te faltan en el cmake y ajusté la velocidad de escritura del pergamino, pero aún no se como hacer que el programa guarde las partidas. ¿Tienes experiencia manejando archivos en vita?

**Comment by skywalker952** [comment]
Otro intemto,perdona entre que lo hago desde el movil y el limite de 25 megas de gmail,no vea la que estoy liandoEl 7 mar. 2021 16:48, luke skywalker <skywalker952@hotmail.com> escribió:Mi port si guardaEl 7 mar. 2021 16:46, Samuel Salinas Almaguer <notifications@github.com> escribió:

he conseguido hacer funcionar Abbey en Vita. Corregí una función que por error redibujaba varias veces la pantalla al hacer una transición de pantallas, agregué un par de sonidos que te faltan en el cmake y ajusté la velocidad de escritura del pergamino, pero aún no se como hacer que el programa guarde las partidas. ¿Tienes experiencia manejando archivos en vita?
